openapi: 3.0.3
components:
  schemas:
    transacao_cartao_credito:
      type: object
      properties:
        transaction_id:
          type: string
        individual_id:
          type: string
        nome_cliente:
          type: string
        numero_conta:
          type: string
        produto_cartao:
          type: string
        numero_cartao_mascara:
          type: string
        bandeira:
          type: string
        event_timestamp:
          type: string
          format: date-time
        estabelecimento:
          type: string
        categoria:
          type: string
        modo_pagamento:
          type: string
        parcelas:
          type: number
        valor_parcela:
          type: number
        valor_total:
          type: number
        status_transacao:
          type: string
